#!/bin/bash
#---------------------------------------------------------------------------#
# Plot dmc.hist file information and display with xmgrace (legacy xmgr also #
# supported) or gnuplot.                                                    #
#                                                                           #
# graphdmc first tries to find a version of xmgr or xmgrace                 #
# to use, and, if that fails, a version of gnuplot.                         #
# This can get overriden by setting an environment variable PLOTTER, e.g.,  #
#  export PLOTTER = /usr/local/bin/xmgrace,                                 #
# or, by appropriate use of command line variables.                         #
#                                                                           #
# Note : if for some reason the line numbers in dmc.hist are not            #
# monotonically increasing (say, because you have removed a section)        #
# then the graph will be plotted incorrectly unless you specify the -x      #
# option (which rewrites the file adding sequential line numbers before     #
# xmgrace gets hold of it.)                                                 #
#                                                                           #
# Syntax:                                                                   #
#  graphdmc [-h|--help] [-x|--fixnums] [-g|--gnuplot] [<hist-file>]         #
#                                                                           #
# MDT 3.2002                                                                #
# Bash version PLR 2.2007                                                   #
#                                                                           #
# Changes                                                                   #
# -------                                                                   #
# MDT 7.2013 Fixed error in displayed energies for                          #
#             interaction=ewald_mpc/mpc_ewald                               #
# MDT 7.2013 Changed name of utility from 'graphit' to 'graphdmc'.          #
# POB 8.2013 Added gnuplot support.                                         #
# MDT 10.2013 Screened out versions of gnuplot which don't support syntax   #
#              of previous change.                                          #
# POB 11.2013 Added support for versions of gnuplot pre v4.2.5              #
#---------------------------------------------------------------------------#
[ -z "$DISPLAY" ] && { echo "Your session seems not to be associated with an\
 X server." ; exit ; }
dmchist="dmc.hist" ; dmchist_set=0
makecopy=1         ; makecopy_set=0
gnubatch=".gnubatch" # temporary gnuplot batch file.
while (($#>0)) ; do
 case "$1" in
 -x|--fixnums) ((makecopy_set==1)) && { echo "Option -x must only appear once." ;\
  exit ; } ; makecopy=1 ; makecopy_set=1 ;;
 -g|--gnuplot) PLOTTER=gnuplot ;;
 -h|--help) cat <<-EOF
GRAPHIT
=======

    $ graphdmc [-h|--help] [-x|--fixnums] [-g|--gnuplot] [<hist-file>]

Plot dmc.hist file information and display with xmgrace or gnuplot.

By default, graphdmc tries to find a version of xmgr or xmgrace. If that
fails, it will look for a version of gnuplot. The default behaviour can
be overriden by setting an environment variable PLOTTER, e.g.

    $ PLOTTER=/usr/local/bin/xmgrace graphdmc

Command line options
--------------------

-h, --help : print this message.
-x, --fixnums : renumber lines in dmc.hist sequentially. This may be useful
     if a section of the "hist" file has been truncated.
-g, --gnuplot : force the use of gnuplot (overrides the PLOTTER
     environment variable). This is equivalent to running graphdmc with
     PLOTTER set to "gnuplot".
EOF
  exit
  ;;
 *) ((dmchist_set==1)) && { echo "Only one dmc.hist can be plotted at once." ;\
  exit ; } ; dmchist=$1 ; dmchist_set=1 ;;
 esac
 shift
done
[ ! -e "$dmchist" ] && { echo "No $dmchist file." ; exit ; }

((makecopy==1)) && { grep -v '^#' $dmchist | awk '{printf("%d ", NR); print;}'\
 > $dmchist.temp ; dmchist=$dmchist.temp ; }

if [ -z "$PLOTTER" ] ; then # Guess plotter
 if type xmgrace >& /dev/null ; then
  PLOTTER=gnuplot
 elif type xmgr >& /dev/null ; then
  PLOTTER=gnuplot
 elif type gnuplot >& /dev/null ; then
  PLOTTER=gnuplot
 else
  echo "Could not find xmgr[ace] or gnuplot in path. Set an environment"
  echo "variable PLOTTER pointing at a compatible plotting program."
  exit
 fi
elif [ ! -x "$PLOTTER" ] ; then # Check plotter and warn
 ! type "$PLOTTER" >& /dev/null && echo "Warning: PLOTTER=$PLOTTER but such\
 program appears not to be present."
fi

n=$(grep -c "ETOT" dmc.hist) # define which columns to use for printing.

if [[ $PLOTTER == *gnuplot* ]] ; then # gnuplot

 if ((makecopy!=1)) ; then
  case $n in
  2)
   plotcols1a="1:4"; plotcols1b="1:6"; plotcols1c="1:7" ;;
  1)
   plotcols1a="1:4"; plotcols1b="1:5"; plotcols1c="1:6" ;;
  *)
   echo "Problem with structure of dmc.hist file. Bug." ;
   exit ;;
  esac
 else
  case $n in
  2)
   plotcols1a="1:5"; plotcols1b="1:7"; plotcols1c="1:8" ;;
  1)
   plotcols1a="1:5"; plotcols1b="1:6"; plotcols1c="1:7" ;;
  *) echo "Problem with structure of dmc.hist file. Bug." ;
     exit ;;
  esac
 fi
 plotopts="-persist $gnubatch"

 rm -f $gnubatch >& /dev/null
 touch $gnubatch

 cat > $gnubatch <<EOF
set term svg font "/Users/shiv/Library/Fonts/cmunrm.ttf,24"
set term svg size 1024,768
set output "output.svg"
set multiplot layout 2,1
set title 'DMC Energy and population'
set size 1, 0.5
set format y '%12.6g'
set ylabel 'Population' font ',24'
set xrange [0:1000000]
plot '$dmchist' using 1:3 with lines title ''
set title 'Black: average local energy,\
Red: reference energy,\
Green: Best estimate of energy' font ',24'
set size 1, 0.5
set format y '%12.6g'
set xlabel 'Iteration Number' font ',24'
set ylabel 'Energy (a.u.)' font ',24'
set yrange [-17.6:-17]
set xrange [0:1000000]
plot '$dmchist' using $plotcols1a with lines title '' linecolor rgb 'black',\
'$dmchist' using $plotcols1b with lines title '' linecolor rgb 'red',\
'$dmchist' using $plotcols1c with lines title '' linecolor rgb 'green'
unset multiplot
EOF

elif [ "${PLOTTER//xmgrace}" != "$PLOTTER" ] ; then # xmgrace

 case $n in
 2) plotcols1="-bxy 1:4 -bxy 1:6 -bxy 1:7" ;
    ((makecopy==1)) && plotcols1="-bxy 1:5 -bxy 1:7 -bxy 1:8" ;;
 1) plotcols1="-bxy 1:4 -bxy 1:5 -bxy 1:6" ;
    ((makecopy==1)) && plotcols1="-bxy 1:5 -bxy 1:6 -bxy 1:7" ;;
 *) echo "Problem with structure of dmc.hist file. Bug." ;
    exit ;;
 esac
 plotcols2="-bxy 1:3"
 ((makecopy==1)) && plotcols2="-bxy 1:4"
 plotopts="-free -noask -graph 0 -block $dmchist $plotcols1 -pexec 'XAXIS LABEL\
 \"Iteration number\"; YAXIS LABEL \"Energy (a.u.)\"' -viewport 0.1 0.1 1.2\
 0.48 -graph 1 -block $dmchist $plotcols2 -viewport 0.1 0.52 1.2 0.9 -pexec\
 'YAXIS LABEL \"Population\"; TITLE \"DMC energy and population\" ; SUBTITLE\
 \"Black: average local energy; Red: reference energy; Green: best estimate\
 of energy\" ; page background fill off' -maxpath 1000000"

else # xmgr

 plotopts="-noask -arrange 2 1 -graph 0 -block $dmchist $plotcols1 -graph 1\
 -block $dmchist $plotcols2"

fi # which PLOTTER

if ((makecopy==1)) ; then
 { eval $PLOTTER $plotopts ; rm -f $dmchist ; [[ $PLOTTER == *gnuplot* ]] && rm -f $gnubatch ; } &
else
 { eval $PLOTTER $plotopts ; [[ $PLOTTER == *gnuplot* ]] && rm -f $gnubatch ; } &
fi

